- src/components/CountryList.js
> Add "+" for  country code in DropDown list

- webpack.dist.config.js
Reverts patw0929/react-intl-tel-input#18
> Revert "Change React global on dist"

- package.json
https://github.com/patw0929/react-intl-tel-input/issues/28
> React shouldn't be a dependency

- src/containers/App.js
- src/containers/IntlTelInputApp.js
- With this, the main App that uses this component can take a select handler
> Add support to `onSelectFlag` callback

- package.json
https://github.com/patw0929/react-intl-tel-input/issues/88
> Moved packages which are used directly in source code into dependencies

- webpack.config.js
> Fixed alias path

- Gruntfile.js
- package.json
> Fix example

- src/components/FlagDropDown.js
- src/containers/IntlTelInputApp.js
Fixed https://github.com/patw0929/react-intl-tel-input/issues/125
> Fixed titleTip

- src/containers/IntlTelInputApp.js
RE: fixes #131. Need to have state of the parent container set based on the disabled props value.
> RE: fixes #131

- src/styles/intlTelInput.scss
Sorry to bother you again but I forgot to add the "!default" flag to path variables. They wouldn't be overridable otherwise.
> Added default to flags variables

- example/index.html
- src/containers/IntlTelInputApp.js
- src/example.js
- src/index.html
- tests/TelInput-test.js
I've added an optional onBlur handler. I've also updated the example and docs pages.
> Added on blur callback handler

- src/containers/IntlTelInputApp.js
* Related issue: #129 isGoodBrowser throws an error when trying to render from server
> Removed unused property isGoodBrowser

- package.json
Added pre-push setting to check lint & test before push.
> Refine workflow

- src/containers/IntlTelInputApp.js
> Properly unbinds function from window's scroll

- package.json
> Fix engines version specification

- src/containers/IntlTelInputApp.js
- src/index.html
- tests/TelInput-test.js
Solves #165. Breaks current API contract.
> Update IntlTelInputApp to allow controlled value from outside

- src/containers/IntlTelInputApp.js
Hey, without this I can't render the component on the server.
> make isMobile isomorphic-friendly

- src/components/IntlTelInputApp.js
> Used value for initial state country flag

- __tests__/TelInput.test.js
- src/components/IntlTelInputApp.js
Update Flag when props value changes
> Add flag update when phones changes through props

- .travis.yml
- README.md
- package.json
- src/index.html
- yarn.lock
also remove hard dependencies against some packages which are already
mentioned as peerDependencies or is only used for development, to give
user more flexibility
> reconfigure packages to bring back compatibility to both react 15 & 16

- __tests__/TelInput.test.js
- src/components/IntlTelInputApp.js
> Update placeholder when receiving new placeholder prop

- .gitignore
- .travis.yml
We should run the lint script in travis to make sure there are no any eslint errors.
> Added `yarn lint` in travis script

- src/components/IntlTelInputApp.js
> Fix added dial code twice

- src/components/IntlTelInputApp.js
> Fixed #208: issue of dial code shows twice in input

- src/components/IntlTelInputApp.js
> fix(disabled): Fixed #268: disabled state don't get updated

- README.md
Fixed some grammatical errors and typos in README.md documentation.
> Improved README.md documentation

- .releaserc
- .travis.yml
The dry-run from #323 was successful. This PR enables automated releases with branch filtering. Commit linting is also enabled to ensure that commit message analysis can be done properly.
> Enabled automated semantic releases

- package.json
Digging further down in `storybook-deployer` rabbit hole.
> ci: storybook token, second try

- .github/workflows/main.yml
- package.json
- yarn.lock
https://github.com/storybookjs/storybook-deployer/issues/77 doesn't seem to have a solution posted and has been open for a while. Trying a couple more things from that discussion thread.
EDIT: It appears that the solution is a bump in `@storybook/storybook-deployer` as well as some hack in how the token it passed.
> ci: more storybook

- README.md
This is an update to the Readme.md file where I have enhanced the contributing section by making few changes to it.
Also, I have added the issue section where the user can file an issue if he/she finds so.
> Enhanced contributing section

- .eslintignore
- .eslintrc.js
- config/env.js
- config/jest/cssTransform.js
- config/jest/fileTransform.js
- config/jest/setup.js
- config/jest/setupTestFramework.js
- config/jest/transform.js
- config/paths.js
- package.json
- src/components/AllCountries.js
- src/components/IntlTelInput.js
- src/components/RootModal.js
- src/components/TelInput.js
- src/components/__tests__/FlagDropDown.test.js
- src/components/__tests__/IntlTelInput.test.js
- src/components/__tests__/RootModal.test.js
- src/components/__tests__/TelInput.test.js
- src/components/__tests__/utils.test.js
- yarn.lock
Updates `eslint` and `lint-staged` to slowly pave the way for #383 and make it an easier jump.
> chore: linting updates

- src/components/IntlTelInput.d.ts
Typo: `seletedCountryData` => `selectedCountryData` 🤦 
Nothing to elaborate.
> fix: amend selectedCountryData typo
