- webpack.dist.config.js
Usually `React` global is exposed capitalized
> Change React global on dist

- src/containers/IntlTelInputApp.js
In React 0.14,
> The props object is now frozen, so mutating props after creating a component element is no longer supported.
(from https://facebook.github.io/react/blog/2015/10/07/react-v0.14.html)
Related issue: https://github.com/patw0929/react-intl-tel-input/issues/32
> Shouldn't modify props after creating a component element

- src/containers/IntlTelInputApp.js
- Having a common class on the wrapper div allows styling to
be defined for both `div.flag-dropdown` and the `input` field
when the dropdown is expanded
- More info https://github.com/jackocnr/intl-tel-input/pull/203
> Add `expanded` class to wrapper div when flags are being displayed

- example/index.html
- src/components/AllCountries.js
- src/components/utils.js
- src/containers/App.js
- src/containers/IntlTelInputApp.js
- src/index.html
- [NOT A REQUIRED PROP] Automatically defaults to data defined in `AllCountries.js`
- Create a country singleton in `AllCountries` so data is processed once, but might take external data now
- Initialize `AllCountries` in `processCountryData` method (so before anything happens)
- `AllCountries` now needs to be referenced as `AllCountries.getCountries()` - update references
*PS:* I know you closed issue #68 but please note that the component still works exactly the same way as before, but it's now possible to configure the data that is displayed
> Allow countries dropdown data to be configurable through `countriesData` prop

- example/index.html
- src/containers/App.js
- src/containers/IntlTelInputApp.js
- src/index.html
- This callback allows users to preprocess the placeholders before setting them. So
it's possible to transform `(408) 123-1234` into `(xxx) xxx-xxxx` for example.
> Define new callback `preprocessPlaceholder` optional prop

- src/components/TelInput.js
- src/containers/IntlTelInputApp.js
- src/index.html
- tests/TelInput-test.js
- Pass all props from `App.js` to `IntlTelInputApp.js` with the spread operator, easier and no need to keep updating it when. Let me know if that's ok, otherwise I can update the PR without this change
> Add `fieldId` config just like `fieldName` exists now

- src/containers/IntlTelInputApp.js
- tests/TelInput-test.js
It only happen when the component is initialized with a value containing a dial code.
> Fix focused input on load

- src/styles/intlTelInput.scss
I added a scss variable to be able to overwrite easily the sprite path in my scss.
> Added scss variable for flags sprite

- src/containers/IntlTelInputApp.js
- tests/TelInput-test.js
Fixes #126. It updates inner input value on components value change. Useful when you want to do some validation on `onPhoneNumberChange` or `onSelectFlag`
> implement state.value change in componentWillReceiveProps

- README.md
This issue has been tripping me up for the better part of a day; though to be fair I'm relatively new to webpack.
I was unable to get it working with the `output.publicPath` setting, but dropping the `sourceMap` option did the trick for me. Hopefully this helps others in the future.
> Add readme note about sourcemaps

- src/components/CountryList.js
- src/containers/IntlTelInputApp.js
- src/index.html
- src/styles/intlTelInput.scss
- tests/TelInput-test.js
When mobile useragent is detected, the flag dropdown is rendered as a
direct child of `document.body`. This might be undesirable for
use-cases when the telephone input must be strictly contained in a
certain DOM element.
Add `useMobileFullScreen` prop to `IntlTelInputApp` which specifies
whether to use the _fullscreen_ rendering for mobile useragents.
`useMobileFullScreen` defaults to `true` and is thus backwards
compatible.
> Add prop to turn off mobile fullscreen

- src/components/TelInput.js
- src/containers/IntlTelInputApp.js
- src/index.html
I have a form containing a phone input and this is the only field that's not being autofilled. It would be nice if we could configure it to allow autocompletion with, e.g.
<IntlTelInput autoComplete={'tel'} />
The default values are setup to be backwards compatible.
> make autocomplete prop configurable

- src/components/TelInput.js
- src/containers/IntlTelInputApp.js
- src/index.html
HTML input element supports few attributes more than it is possible to configure via the IntlTelInputApp props. Since adding all of them seems to be a little bit of an overhead, new telInputProps should provide usage flexibility (e.g. maxLenght, required, etc.).
> Pass arbitrary props to the tel input element

- src/components/CountryList.js
Since preferred countries can be in double with actual countries from the list, react keys can be doubled, which results in a warning in the console.
I fixed that by adding a key prefix for preferred countries.
> Fixed preferred countries key

- src/components/IntlTelInputApp.js
When typing a number and specifying a country code, the flag icon turns blank. This is more noticeable when using onlyCounties since a country may not be in the list. eg => +44 when the UK is not in the list results in a blank flag.
This also occurs when you are in mid type of providing a country code. +4 does not exist. +44 does. So while +4 is showing, a blank flag will be displayed.
> Blank Flag HotFix

- __tests__/TelInput.test.js
- src/components/IntlTelInputApp.js
Currently country code in the input field can't be deleted on a controlled or uncontrolled component
https://github.com/patw0929/react-intl-tel-input/issues/197
If the user deletes the numbers of the country code and only has "+" in value. updateFlagFromNumber will populate the flag to the default country which in turn will populate the input field with the default code. 
I've removed the setting a default country code because the default country is always the currently selected flag and seems to be redundant (Let me know if i'm wrong ).
Here is where default country is set: https://github.com/MatthewAnstey/react-intl-tel-input/blob/c731a6b913b5d8852d886c4b0e35ae7cbc7c37b7/src/components/IntlTelInputApp.js#L241 on every flag change, making it redundant. I think its redundant because its …
> Allow country code to be deleted

- src/components/IntlTelInputApp.js
> Fix runtime error when this.tel is null

- __tests__/TelInput.test.js
- src/components/IntlTelInputApp.js
> Handle placeholder and customPlaceholder change

- config/babel.prod.js
- package.json
- yarn.lock
Remove proptypes from peer dependency (was throwing warning which brought me here 😄 ). As per: https://github.com/facebook/prop-types/issues/44#issuecomment-299238787
Moved proptypes to dependencies (similar to the style-proptype lib).
Added babel plugin to remove proptypes from dist, as they aren't executed.
main.js 76kb -> 74kb.
> Move Prop-types out of peer dependency. remove proptypes in dist.

- __tests__/TelInput.test.js
- src/components/IntlTelInputApp.js
As we are attaching global "expanded" class to the wrapper
when countries are open, this class is not being removed once
country is selected and dropdown closed.
Fixes #218
> [#218] Fix expanded class not being removed from wrapper

- __tests__/utils.test.js
- src/components/IntlTelInputApp.js
- src/components/utils.js
`findIndex` is not available in IE 11.
There is `core-js` polyfill available [1], however would like to avoid
using it as our app runs on top of other sites as a widget and we do not
want to define any kinds of globally available functions.
Instead use `some` which is implemented in IE 11.
[1]: https://github.com/zloirock/core-js/tree/v2#ecmascript-6-array
> Add findIndex implementation for IE 11

- __tests__/utils.test.js
- src/components/IntlTelInputApp.js
- src/components/TelInput.js
- src/components/utils.js
Fixing Cursor [Issue#205](https://github.com/patw0929/react-intl-tel-input/issues/205)
@patw0929
> Fix cursor Issue#205

- src/components/IntlTelInputApp.js
Syntax issue:
`parseFloat` shouldn't has the second argument.
ref: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/parseFloat
Should removed it.
> Removed second argument of parseFloat

- .npmignore
> [Update] npmignore updated with file list

- src/components/IntlTelInputApp.js
Hi guys, 
i use your component and noticed that in difference from origin widget it not close country list when click on the same flag button. This creates inconvenience in UX when switch from jQuery to React because many users wait same behavior.
I didn't dive deep into logic and find few places where it can be fixed. 
It will be great either you make own fixes or use my and this bug will be fixed 👌
Thanks
> Hide country list when click on flag button

- src/components/FlagDropDown.js
Right now when `allowDropdown` is set to false, user can still click on the flag and list of countries is shown. This change makes sure `allowDropdown` is set to `true` before showing list of countries.
> Fixes #235: Show countrylist when allowDropdown flag is set to true

- config/env.js
- package.json
- src/components/CountryList.js
- src/components/IntlTelInputApp.js
- src/components/TelInput.js
- src/components/__tests__/FlagDropDown.test.js
- src/components/__tests__/RootModal.test.js
- src/components/__tests__/TelInput.test.js
- src/components/__tests__/utils.test.js
- src/example.js
* Fixed the bugs when eslint & prettier running in lint-staged
* Fixed coding style in current codebase with `prettier:all` & `eslint --fix`
> Fixed eslint prettier script

- src/components/IntlTelInputApp.js
- src/example.js
Fixed the issue of not updating value when value is empty string.
1. We should let empty value also can be updated in `getDerivedStateFromProps`.
2. No need to `setState` in `blurHandler` event in example.
---
> Fixed not update value issue when value is empty string

- src/components/TelInput.js
This commit fixed an issue like this. There are two Inputs in a form on my login page. The phone number input will get focus after entering every one character in password input.  Because the form managed the inputs together.
> update cursor position after focused

- src/components/RootModal.js
- src/components/__tests__/RootModal.test.js
We should use `createPortal` API which provide by React to implement the mobile flag modal feature instead.
Reference: [https://reactjs.org/docs/portals.html](https://reactjs.org/docs/portals.html)
> Use createPortal API to implement RootModal

- src/components/IntlTelInputApp.js
- src/components/TelInput.js
As #252 said, when pasting a full number in international mode, the flag won't update.
But it works great when typing from the beginning.
In #252, @Samb102 provided their [workaround](https://github.com/patw0929/react-intl-tel-input/issues/252#issuecomment-458234735) which is called via ref.
This pull request is based on their workaround but without ref.
Before fix:
After fix:
> Fixed the issue of pasting number to text input cannot update flag in international mode

- .travis.yml
- package.json
Fixes travis build for storybook according to documentation [deploying-storybook-as-part-of-a-ci-service](https://github.com/storybooks/storybook-deployer#deploying-storybook-as-part-of-a-ci-service)
> fix(storybook-deploy): Fixed the storybook deployment script in travis

- .storybook/webpack.config.js
- yarn.lock
Fixed the public path of storybook's file loader.
When we've deployed storybook build files to github pages, we would found that the flags image were missing.
That's because the storybook's webpack file-loader public path setting is set to `'/'`, and the github page of this repo has its subfolder `/react-intl-tel-input/`.
It should be relative path `'./'` here.
> Fix: storybook's public path

- src/components/IntlTelInput.js
> Fix(272): Updating Allowdropdown after mount

- README.md
Fixes #293 
Removed bash highlighting for npm/yarn command in README
> Removed bash highlighting for npm/yarn commands in README

- src/components/IntlTelInput.js
- src/components/TelInput.js
There were an issue with actions triggered on onChange and onPaste. Both of them were overlapping and causing multiple rerenders, but also error with concatenating numbers onPaste (instead of replacing). Only onChange was needed, so onPaste function and prop was deleted.
> fixed bug with pasting number over another number

- src/components/IntlTelInput.js
When using `formatOnInit` in conjunction with `onPhoneNumberChange`, a bug causes the latter callback to be invoked with a value from the not-yet-formatted previous state.
This change fixes this behavior and notifies the callback with the updated, formatted value.
I have tried to write two test cases (default and `formatOnInit=false`), but unfortunately, my knowledge of Enzyme is too limited 😥️ The behavior relies on libphonenumber-js-utils to be done loading, so the test cases must run after the deferred are resolved…
> Fix: invoke onPhoneNumberChange callback with formatted value on init instead of unformatted value from previous state

- .storybook/stories/3.Playground/Playground.stories.js
- src/components/IntlTelInput.js
- src/components/TelInput.js
- src/components/__tests__/TelInput.test.js
Added optional `onPhoneNumberFocus` function, similar to `onPhoneNumberBlur`.
Added `onPhoneNumberFocus` because it's not possible to extended `onFocus` in `telInputProps` property due to `onFocus` being overwritten in `src/components/TelInput.js`. There is an open PR addressing the same thing in #239, but it has been stale for some time and lack tests.
> Add optional onPhoneNumberFocus function

- src/components/IntlTelInput.js
https://www.loom.com/share/a4d1e5295b0341ecb3da4a2c019e32b4
** Pls see the video.  This PR potentially fixes the following bug:
For some localities (I've only identified Russia), when a user deletes numbers `window.intlTelInputUtils.formatNumber` behaves incorrectly.
window.intlTelInputUtils.formatNumber('8 (444) 444-44-4', 'ru', 2)  ==> "8 (844) 444-44-44"
window.intlTelInputUtils.formatNumber('8 (844) 444-44-4', 'ru', 2)  ==> "8 (884) 444-44-44"
window.intlTelInputUtils.formatNumber('8 (884) 444-44-4', 'ru', 2)  ==> "8 (888) 444-44-44"
window.intlTelInputUtils.formatNumber('8 (888) 44-44-4', 'ru', 2)  ==> "8 (888) 844-44-44"
window.intlTelInputUtils.formatNumber('8 (888) 84-44-4', 'ru', 2)  ==> "8 (888) 884-44-44"
. . . and so on, until all digits are '8'.
See video above
Adds a check …
> Bug fix: Bypass formatNumber if user is deleting

- src/components/CountryList.js
- src/components/FlagBox.js
As part of removing the extraneous use of Webpack in #314 , I noticed that the usage of `scss` in styling forces the project to be bundled so that a style loader can take care of the style. Before `scss` can be replaced by something more appropriate for the module context (versus having a bundled webapp), there's a few refactors that can be done to simplify the logic, lighten the code and speed up later development.
This breaks out the `FlagBox` component our of `CountryList` to separate concerns and extract code that is purely presentational in nature from containers that are more involved in business logic. As far as the outside API is concerned, this is a no-op, but it'll benefit developer velocity and further work.
- ~[ ] I have updated the documentation accordingly.~
- ~[ ] I have …
> Extract Flagbox

- package.json
- src/components/CountryList.js
- src/components/CountryList.styles.js
- src/components/FlagBox.js
- src/components/FlagDropDown.js
- src/components/FlagDropDown.styles.js
- src/components/IntlTelInput.js
- src/components/__tests__/FlagDropDown.test.js
- src/components/__tests__/TelInput.test.js
- src/components/__tests__/utils.test.js
- src/components/utils.js
- src/styles/intlTelInput.scss
- yarn.lock
See #315.
This trims code around the `CountryList` quite a bit and starts the move from scss to `styled-components`. It also starts to tackle the binding of style <> functionality around classes by extract the style from some of them so that their functional role can be refactored away separately.
From the outside perspective, this is a no-op.
- ~[ ] I have updated the documentation accordingly.~
- ~[ ] I have added tests to cover my changes.~
Did cursory QA in Chrome and Firefox to ensure that no regression seeped in, nothing to report.
> Refactoring around `CountryList`

- src/components/IntlTelInput.js
- src/components/TelInput.js
- src/components/__tests__/utils.test.js
- src/components/constants.js
- src/components/utils.js
These are some more cleaning changes that reduce redundancy and work towards separating concerns in the codebase. Since `classList` has been well-supported and the utils included in the utility file were more than 10 years old now, I purged them in favour of the more direct `classList`'s `add` and `remove`.
- ~[ ] I have updated the documentation accordingly.~
- ~[ ] I have added tests to cover my changes.~
> Extract constants and purge superfluous utils

- .storybook/stories/1.GettingStarted/GettingStarted.stories.js
- .storybook/stories/2.Props/Props.stories.js
- .storybook/stories/3.Playground/Playground.stories.js
- .storybook/stories/5.CustomStyle/CustomStyle.stories.js
- .storybook/stories/6.GeoIP/GeoIP.stories.js
- src/components/IntlTelInput.js
In order to allow for users to use their own stylesheets (or to just use the sample provided one), we can take off any SASS imports from within the component. This is something the old Webpack setup used to do.
It's reasonable to assume that the consumer's React apps will have a Webpack-like system, and that they will use something like `node-sass` to handle proper stylesheet loading.
> Removing SCSS import from components

- .eslintrc.js
- jest.config.js
- package.json
- src/components/AllCountries.js
- src/components/CountryList.js
- src/components/FlagBox.js
- src/components/FlagDropDown.js
- src/components/IntlTelInput.js
- src/components/RootModal.js
- src/components/TelInput.js
- src/components/__tests__/FlagDropDown.test.js
- src/components/__tests__/RootModal.test.js
- src/components/__tests__/TelInput.test.js
- src/components/__tests__/utils.test.js
- src/components/constants.js
- yarn.lock
This PR consolidates the ESLint  and Prettier flows so that we can just run `eslint --fix` to also fix Prettier errors. It'll also prevent disparities between the two rulesets that would otherwise conflict.
The large changeset is due to running `eslint --fix` across the board, which will now also apply `prettier` rules and fix them.
> Cleaning up ESLint / prettier configs and uniting them

- package.json
- yarn.lock
A fair amount of `devDependencies` are no longer in use, this PR removes them from the package file and updates the yarn lockfile to reflect their removal.
This should be a no-op from outside, test/lint/storybook was verified to ensure that no regressions happen there.
> Cleaning up devDependencies

- package.json
- yarn.lock
Self-explanatory. Filed as a `fix` because it addresses false positives in phone validation.
> Update `libphonenumber-js-utils` to latest

- src/components/IntlTelInput.js
- src/components/__tests__/IntlTelInput.test.js
Custom class prop updates should not be cumulative.
The classes passed via `containerClassName` were previously appended to a component property (`wrapperClass`) which did not flush the custom classes on rerender if the `containerClassName` prop was changed. This led to scenarios where the custom class passed by a user would change, the prop would change, and the resulting applied class would be the sum of the previous prop values instead of having the new custom class replace the old.
This was addressed by not saving the `containerClassName` value to `wrapperClass` but instead keeping it in `render`. This ensures that if the prop changes, the resulting classname will be updated accordingly.
This addresses #344.
> fix: custom class prop update should not be cumulative

- src/components/IntlTelInput.js
- src/components/__tests__/FlagDropDown.test.js
Currently, we're checking for localStorage's presence but not its
actual usability. In some scenarios, browsers can disallow
`localStorage` to be called upon and in such cases, the library will hard
crash.
In this change, I added a catch statement to intercept these errors and
return an empty string when `localStorage` cannot be called upon.
> fix: library crashes when localStorage is not callable

- .github/workflows/main.yml
Addresses [this issue](https://github.com/storybookjs/storybook-deployer/issues/77), which came up when using the Storybook deployer in CI.
> ci: github actor

- package.json
- yarn.lock
This removes `@commitlint/travis-cli`, now unused.
> chore: remove unused commitlint/travis-cli dep
